name: Build
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
        types:
            - synchronize
            - ready_for_review

jobs:
    quality_assurance:
        name: Quality Assurance
        if: >-
            github.event_name == 'push' || 
            (github.event_name == 'pull_request' && !github.event.pull_request.draft)
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                php-versions: ['8.1']
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    coverage: none
                    tools: composer:v2
                env:
                    update: true

            -   name: Get composer cache directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache composer dependencies
                uses: actions/cache@v3
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-
            -   name: Install dependencies
                run: composer install --no-interaction --no-progress

            -   name: Dump environment variables into .env.local.php
                run: composer dump-env test

            -   name: Run Quality Assurance
                run: composer run-script qa
